---
title: "AN588-Week-2"
author: "Gentry Miller"
format: html
editor: visual
date: "23 Jan, 2025"
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages("stringr")
library("stringr")
```

# Challenges

## Challenge 1

```{r}
v1 <- c("Stately,", "plump", "Buck", "Mulligan", "came", "from", "the", "stairhead,", "bearing", "a", "bowl", "of", "lather", "on", "which", "a", "mirror", "and", "a", "razor", "lay", "crossed")
#v1
```

```{r}
# I tried to use str_split() and str_split_i() but it was only pulling characters instead of the whole sub-string. When I set the boundary to word, it pulled NA.
v2 <- v1[seq(0, length(v1), 3)]
v2
gsub("[[:punct:]]", "", v1)
```

## Challenge 2

```{r}
m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
```

```{r}
x <- matrix(data = c(m[,2], m[,3], m[,6]), nrow = 8, ncol = 3, byrow = FALSE)
```

```{r}
x <- matrix(data = m[6:8,], nrow = 3, ncol = 10, byrow = FALSE) 
```

```{r}
x <- matrix(data = m[2:6,2:9], nrow = 5, ncol = 8)
```

## Challenge 3

```{r}
a <- array(400:1, dim = c(5, 5, 4, 4))
```

```{r}
a[1, 1, 1, 2]
a[2, 3, 2,]
a[1:5, 1:5, 3, 3]
```

### 3.2.1

`a[1, 1, 1, 2]` returns 300

### 3.2.2

`a[2, 3, 2, ]` returns a vector containing 364, 264, 164, and 64

### 3.2.3

`a[1:5, 1:5, 3, 3]` returns a 5x5 matrix of the first 5 values for the first and second dimensions of a at the third value of the third and fourth dimensions.

## Overwriting

```{r}
# Replaces a single val at m[7,1]
m[7, 1] <- 564
# Replaces the 8th column of m with all 2's
m[, 8] <- 2
# Replaces the values in rows 2-5 and columns 4-8 with 1
m[2:5, 4:8] <- 1
# Replaces the vals in row 2 col 4-8 with 20, row 3 cols 4-8 with 19, etc.
m[2:5, 4:8] <- c(20, 19, 18, 17)
# Replaces rows 2-5 and cols 4-8 with a new matrix of decreasing ints from 20-1 by row
m[2:5, 4:8] <- matrix(data = c(20:1), nrow = 4, ncol = 5, byrow = TRUE)
# replaces the vals in col 8 with alternating chars a and b and changes the data type of every value in the matrix to character
m[, 8] <- c("a", "b")
```

## Lists and Data Frames

```{r}
s <- c("this", "is", "a", "vector", "of", "strings")
m <- matrix(data=1:40, nrow=5, ncol=8)
b <- FALSE
l <- list(s, m, b)
```

```{r}
l[[2]]
```

```{r}
l[[2]][2, 6]
```

```{r}
l[c(1,3)]
```

```{r}
str(l)
names(l) <- c("string", "matrix", "logical")
names(l)
l$string
l$matrix[3, 5]
```
